name: default

kind: pipeline
type: docker

steps:

- name: run
  image: hseeberger/scala-sbt:8u265_1.4.4_2.13.4
  # environment:
  #   kafkaHost: 192.168.1.35
  #   kafkaPort: 9092
  #   kafkaRecordTopic: records
  #   csvPath: ./src/main/resources/data/peace.csv
  commands:
    - sbt "alerts/compile"
    - sbt "producer/compile"
    - sbt "storage/compile"
  when:
    branch:
    - main