version: '2.1'
services:

  zookeeper:
    restart: always
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    restart: always
    image: 'bitnami/kafka:latest'
    container_name: kafka
    ports:
      - '9092:9092'
    environment: 
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CREATE_TOPICS="records:1:1,alerts:1:1"
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=EXTERNAL://localhost:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=EXTERNAL
    depends_on:
      - zookeeper

  arangodb:
    restart: always
    image: arangodb/arangodb
    container_name: arangodb
    ports:
      - ${ARANGO_PORT}:8529
    environment: 
      - ARANGO_ROOT_PASSWORD=${ARANGO_PASSWORD}

  alerts:
    build: 
      context: ./
      dockerfile: ./Dockerfile
    command: sbt "alerts/run"
    environment: 
      - kafkaHost=${URI}
      - kafkaPort=${KAFKA_PORT}
      - kafkaAlertTopic=alerts
      - telegramBotToken=${TELEGRAM_TOKEN}
      - telegramChatID=${TELEGRAM_CHATID}
    depends_on:
      - kafka
    network_mode: host

  storage:
    build: 
      context: ./
      dockerfile: ./Dockerfile
    command: sbt "storage/run"
    environment: 
      - kafkaHost=${URI}
      - kafkaPort=${KAFKA_PORT}
      - kafkaRecordTopic=records
      - arangoHost=${URI}:${ARANGO_PORT}
      - arangoUser=${ARANGO_USER}
      - arangoPassword=${ARANGO_PASSWORD}
    depends_on:
      - arangodb
      - kafka
      - peaceapi
    network_mode: host

  producer:
    build: 
      context: ./
      dockerfile: ./Dockerfile
    command: sbt "producer/run"
    environment: 
      - kafkaHost=${URI}
      - kafkaPort=${KAFKA_PORT}
      - kafkaRecordTopic=records
      - kafkaAlertTopic=alerts
      - csvPath=resources/data/peace.csv
      - csvPathAlert=resources/data/peaceAlert.csv
      - GRPC_URL=${URI}
      - GRPC_PORT=${GRPC_PORT}
    depends_on:
      - kafka
      - peaceapi
    network_mode: host

  stats:
    build: 
      context: ./
      dockerfile: ./Dockerfile
    command: sbt "stats/run"
    environment: 
      - arangoHost=${URI}:${ARANGO_PORT}
      - arangoUser=${ARANGO_USER}
      - arangoPassword=${ARANGO_PASSWORD}
    depends_on:
      - arangodb
    network_mode: host

  peaceapi:
    image: thomaslacaze/peace-api:latest
    container_name: peace-api
    restart: always
    ports: 
      - ${GRPC_PORT}:8083